### ISSUE TITLE
Weird route taken at motorway junction in Reims, FR

### ISSUE THREAD

**Issue by AlbertJP** [valhalla/sif#122]
This is quite a weird route to take around a junction:
![screenshot from 2016-07-17 21 57 41](https://cloud.githubusercontent.com/assets/1248033/16902796/bfc39ad0-4c69-11e6-9062-23d25c3b749b.png)

It is only shown when the start and end of the route are far away from Reims (~100km or more). Choosing start and end nearby gives me a much shorter route:
![screenshot from 2016-07-17 22 01 21](https://cloud.githubusercontent.com/assets/1248033/16902801/0933ca50-4c6a-11e6-92db-2e5319dbcd29.png)

**Comment by dnesbitt61** [comment]
This is due to not having a connection that remains on highway = primary, trunk or motorway. On longer routes for automobiles, lower classed roads are excluded except for near the origin or destination. Looks like there is no good way to get onto A-34 from N244 when coming from the north without going through the roundabout on D8 (which is a lower classed road). Making the roundabout highway=primary would fix this unless there is another better way to get onto A-34.

**Comment by AlbertJP** [comment]
Turns out (google maps) that a N244>A34 slip road has opened. I've put a note on the map to get this fixed.
