### ISSUE TITLE
Short piece of road costs 10 minutes for no apparent reason

### ISSUE THREAD

**Issue by AlbertJP** [valhalla/sif#71]
I don't know if this is posted at the right project, feel free to point me to the right place if it does not belong here.

When traversing bridge https://www.openstreetmap.org/way/56501888 or https://www.openstreetmap.org/way/7230690, there is a problem with costing. A car route across either of them takes 10 minutes for just a short stretch of motorway.

**Comment by dnesbitt61** [comment]
This is due to a country crossing indicated by the administrative boundaries. We have a default 10 minute cost to change from one country into another. This can be overridden in the request by adding a costing_option "country_crossing_cost" of 0. So you have a workaround if your application targets users in countries where border crossings do not typically cause travel delays.

We are considering use of other tags to  identify border crossings where a physical barrier exists and only apply costs when those are encountered - we just don't know how reliable those tags will be.  We will look to make some updates in this area in the near future.

**Comment by kevinkreiser** [comment]
We are having a look at this barrier=border_control as it seems this is what we were shooting for. A quick look in overpass turbo shows the tag has good coverage in the US and places we are familar with in Europe:

http://overpass-turbo.eu/s/ctQ

**Comment by AlbertJP** [comment]
@dnesbitt61 This road I am referring to, is not the country crossing, but some 5 km away from it.
When I plan a route from NL to B, the router directs me off the motorway the last exit before this viaduct, then brings me back on the motorway in Belgium, so the route crosses the border anyway.
In your description any border crossing between NL and B should cost equally much, so the router should not get me off the motorway to cross the same border at a different place.
It is of course true that this country crossing does not need 10 minutes of time, but the 10 minute cost is not correctly applied here and that I see as a bug. Planning a route for 500 metres over one of the ways I mentioned already gives me a 10 minute cost, without crossing any border.
